import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const galmuri9 = localFont({
    src: "./fonts/Galmuri9.woff2",
    variable: "--font-galmuri9",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${galmuri9.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
