import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/main/Header";
import Footer from "@/components/main/Footer";
import Sidebar from "@/components/main/Sidebar";

// 메타데이터 설정 (페이지 제목, 설명, 아이콘)
export const metadata: Metadata = {
    title: "SeHi's Next Front",
    description: "Generated by create next app",
    icons: "SeHi_Logo_NoTitle.svg",
};

// 레이아웃 컴포넌트 (공통으로 사용할 레이아웃)
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet"
                />
            </head>
            <body suppressHydrationWarning={true}>
                {/* 공통 Header */}
                <Header />
                <div className="flex px-10 py-2">
                    {/* 공통 Sidebar */}
                    {/* <Sidebar /> */}
                    <main className="dark:invert h-[calc(100vh-70px)] flex-1 bg-gray-300 rounded-t-xl overflow-auto flex flex-row justify-between gap-2">
                        <Sidebar />
                        {/* Rendering 될 내용 */}
                        {children}
                    </main>
                </div>
                {/* 공통 Footer */}
                <Footer />
            </body>
        </html>
    );
}
